export const seedBanners = [
  {
    title: 'Moxfood Premium Healthy Seeds & Superfoods',
    subtitle: 'Buy 100% Raw & Roasted Pumpkin Seeds, Chia Seeds, Sunflower Seeds & Seed Mixes!',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
    link: '/products?category=seeds-superfoods',
    buttonText: 'Shop Healthy Seeds',
    isActive: true,
    order: 1,
  },
  {
    title: 'Organic Chia & Pumpkin Seeds Range',
    subtitle: 'Rich in Omega-3, Protein & Fibre for Daily Immunity and Health',
    image: 'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=1400&q=80',
    link: '/products?category=seeds-superfoods',
    buttonText: 'Explore Seeds Deals',
    isActive: true,
    order: 2,
  },
  {
    title: 'Super Saver Ration & Grocery Combo',
    subtitle: 'Aashirvaad Atta, Cooking Oil, Toor Dal & Tea at Wholesale Rates',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1400&q=80',
    link: '/products?category=atta-rice',
    buttonText: 'Buy Ration Combos',
    isActive: true,
    order: 3,
  },
];

export const seedCategories = [
  {
    name: 'Healthy Seeds & Superfoods',
    altNameGujarati: 'ડ્રાય સીડ્સ અને હેલ્ધી ખોરાક',
    slug: 'seeds-superfoods',
    image: 'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=600&q=80',
    iconName: 'Leaf',
  },
  {
    name: 'Atta, Rice & Grains',
    altNameGujarati: 'લોટ, ચોખા અને અનાજ',
    slug: 'atta-rice',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    iconName: 'Wheat',
  },
  {
    name: 'Edible Oil & Masalas',
    altNameGujarati: 'તેલ અને મસાલા',
    slug: 'oil-masala',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    iconName: 'Flame',
  },
  {
    name: 'Dairy & Breakfast',
    altNameGujarati: 'ડેરી અને સવારનો નાસ્તો',
    slug: 'dairy-bakery',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    iconName: 'Milk',
  },
  {
    name: 'Snacks & Namkeen',
    altNameGujarati: 'નાસ્તો અને નમકીન',
    slug: 'snacks',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=600&q=80',
    iconName: 'Cookie',
  },
  {
    name: 'Tea, Coffee & Drinks',
    altNameGujarati: 'ચા અને પીણાં',
    slug: 'beverages',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    iconName: 'Coffee',
  },
];

export const seedProducts = [
  // Moxfood Healthy Seeds Range with Multiple Weight Options
  {
    name: 'Moxfood Raw Pumpkin Seeds (AAA Grade)',
    altNameGujarati: 'મોક્સફૂડ દેશી પમ્પકિન સીડ્સ (કોળા ના બી)',
    category: 'seeds-superfoods',
    price: 199,
    mrp: 260,
    stock: 100,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 199, mrp: 260, stock: 100 },
      { unit: '500 g', price: 380, mrp: 500, stock: 60 },
      { unit: '1 kg', price: 720, mrp: 950, stock: 40 },
    ],
    images: [
      'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=600&q=80',
    ],
    description: '100% Natural raw green Pumpkin Seeds rich in Zinc, Magnesium, and Antioxidants for daily immunity.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Moxfood Organic Raw Chia Seeds',
    altNameGujarati: 'ઓર્ગેનિક ચિયા સીડ્સ (ચિયાના બીજ)',
    category: 'seeds-superfoods',
    price: 180,
    mrp: 230,
    stock: 90,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 180, mrp: 230, stock: 90 },
      { unit: '500 g', price: 340, mrp: 440, stock: 50 },
      { unit: '1 kg', price: 650, mrp: 850, stock: 30 },
    ],
    images: [
      'https://images.unsplash.com/photo-1514944288352-1ee824ae44a7?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Premium black Chia Seeds rich in Omega-3 fatty acids, dietary fibre, and calcium for weight management.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Moxfood Raw Sunflower Seeds',
    altNameGujarati: 'સૂર્યમુખીના બી (Sunflower Seeds)',
    category: 'seeds-superfoods',
    price: 150,
    mrp: 195,
    stock: 85,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 150, mrp: 195, stock: 85 },
      { unit: '500 g', price: 280, mrp: 370, stock: 45 },
      { unit: '1 kg', price: 520, mrp: 700, stock: 25 },
    ],
    images: [
      'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Crispy raw peeled Sunflower Seeds rich in Vitamin E, Selenium, and Healthy Fats for heart health.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Moxfood Raw Flax Seeds (Alsi)',
    altNameGujarati: 'અળસીના બી (Flax Seeds / Alsi)',
    category: 'seeds-superfoods',
    price: 120,
    mrp: 160,
    stock: 110,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 120, mrp: 160, stock: 110 },
      { unit: '500 g', price: 220, mrp: 300, stock: 70 },
      { unit: '1 kg', price: 410, mrp: 580, stock: 35 },
    ],
    images: [
      'https://images.unsplash.com/photo-1514944288352-1ee824ae44a7?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Clean whole brown Flax Seeds high in Lignans, Fibre, and Omega-3 for digestive wellness.',
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Moxfood 7-in-1 Super Seeds Mix (Roasted & Salted)',
    altNameGujarati: '૭-ઈન-૧ સુપર સીડ્સ મિક્સ (રોસ્ટેડ નાસ્તો)',
    category: 'seeds-superfoods',
    price: 240,
    mrp: 320,
    stock: 75,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 240, mrp: 320, stock: 75 },
      { unit: '500 g', price: 450, mrp: 600, stock: 40 },
      { unit: '1 kg', price: 860, mrp: 1150, stock: 20 },
    ],
    images: [
      'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Power-packed blend of Pumpkin, Chia, Sunflower, Flax, Watermelon, Muskmelon, and Sesame Seeds.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Moxfood Raw Watermelon Seeds (Tarbooz Seeds)',
    altNameGujarati: 'તરબૂચના બીજ (Watermelon Seeds)',
    category: 'seeds-superfoods',
    price: 165,
    mrp: 210,
    stock: 65,
    unit: '250 g',
    variants: [
      { unit: '250 g', price: 165, mrp: 210, stock: 65 },
      { unit: '500 g', price: 310, mrp: 400, stock: 35 },
      { unit: '1 kg', price: 590, mrp: 760, stock: 20 },
    ],
    images: [
      'https://images.unsplash.com/photo-1509358271058-acd02cc93858?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Peeled white Watermelon Seeds rich in Protein and Essential Minerals for healthy skin and energy.',
    isFeatured: false,
    isTrending: true,
  },

  // Grocery Ration Essentials
  {
    name: 'Aashirvaad Shudh Chakki Atta',
    altNameGujarati: 'આશીર્વાદ શુદ્ધ ચક્કી લોટ',
    category: 'atta-rice',
    price: 365,
    mrp: 410,
    stock: 45,
    unit: '5 kg',
    variants: [
      { unit: '5 kg', price: 365, mrp: 410, stock: 45 },
      { unit: '10 kg', price: 710, mrp: 800, stock: 30 },
    ],
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    ],
    description: '100% pure whole wheat flour chakki fresh for soft rotis.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Fortune Sunlite Refined Sunflower Oil',
    altNameGujarati: 'ફોર્ચ્યુન સનલાઈટ રિફાઈન્ડ તેલ',
    category: 'oil-masala',
    price: 135,
    mrp: 160,
    stock: 60,
    unit: '1 Litre',
    variants: [
      { unit: '1 Litre', price: 135, mrp: 160, stock: 60 },
      { unit: '5 Litre Pouch', price: 650, mrp: 780, stock: 25 },
    ],
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Light and healthy refined sunflower oil, enriched with Vitamin A & D.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Desi Premium Toor Dal',
    altNameGujarati: 'દેશી પ્રીમિયમ તુવેર દાળ',
    category: 'atta-rice',
    price: 160,
    mrp: 185,
    stock: 50,
    unit: '1 kg',
    variants: [
      { unit: '1 kg', price: 160, mrp: 185, stock: 50 },
      { unit: '5 kg Pack', price: 775, mrp: 900, stock: 25 },
    ],
    images: [
      'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Unpolished protein-rich Toor Dal for delicious homemade dal.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Wagh Bakri Premium Leaf Tea',
    altNameGujarati: 'વાઘ બકરી પ્રીમિયમ ચા',
    category: 'beverages',
    price: 260,
    mrp: 290,
    stock: 35,
    unit: '500 g',
    variants: [
      { unit: '250 g', price: 135, mrp: 150, stock: 50 },
      { unit: '500 g', price: 260, mrp: 290, stock: 35 },
      { unit: '1 kg', price: 500, mrp: 560, stock: 20 },
    ],
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Strong, rich aroma tea for authentic Masala Chai.',
    isFeatured: true,
    isTrending: true,
  },
];
