export const seedBanners = [
  {
    title: 'Super Saver Ration Combo Deals',
    subtitle: 'Save up to 25% on Whole Wheat Atta, Edible Oil & Desi Pulses!',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
    link: '/?category=atta-rice',
    buttonText: 'Shop Ration Deals',
    isActive: true,
    order: 1,
  },
  {
    title: 'Fresh & Pure Cooking Oils',
    subtitle: 'Fortune, Emami & Pure Groundnut Oil at Wholesale Rates',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1400&q=80',
    link: '/?category=oil-masala',
    buttonText: 'Explore Oils & Spices',
    isActive: true,
    order: 2,
  },
  {
    title: 'Premium Tea & Daily Breakfast',
    subtitle: 'Wagh Bakri, Taj Mahal Tea & Amul Fresh Dairy Products',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1400&q=80',
    link: '/?category=beverages',
    buttonText: 'Buy Tea & Snacks',
    isActive: true,
    order: 3,
  },
];

export const seedCategories = [
  {
    name: 'Atta, Rice & Grains',
    altNameGujarati: '',
    slug: 'atta-rice',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    iconName: 'Wheat',
  },
  {
    name: 'Edible Oil & Masalas',
    altNameGujarati: '',
    slug: 'oil-masala',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    iconName: 'Flame',
  },
  {
    name: 'Dairy & Breakfast',
    altNameGujarati: '',
    slug: 'dairy-bakery',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    iconName: 'Milk',
  },
  {
    name: 'Snacks & Namkeen',
    altNameGujarati: '',
    slug: 'snacks',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=600&q=80',
    iconName: 'Cookie',
  },
  {
    name: 'Tea, Coffee & Drinks',
    altNameGujarati: '',
    slug: 'beverages',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    iconName: 'Coffee',
  },
  {
    name: 'Cleaning & Household',
    altNameGujarati: '',
    slug: 'cleaning',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    iconName: 'Sparkles',
  },
];

export const seedProducts = [
  {
    name: 'Aashirvaad Shudh Chakki Atta',
    altNameGujarati: '',
    category: 'atta-rice',
    price: 365,
    mrp: 410,
    stock: 45,
    unit: '5 kg',
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    ],
    description: '100% pure whole wheat flour chakki fresh for soft rotis.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Fortune Sunlite Refined Sunflower Oil',
    altNameGujarati: '',
    category: 'oil-masala',
    price: 135,
    mrp: 160,
    stock: 60,
    unit: '1 Litre',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Light and healthy refined sunflower oil, enriched with Vitamin A & D.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Fortune Everyday Basmati Rice',
    altNameGujarati: '',
    category: 'atta-rice',
    price: 450,
    mrp: 520,
    stock: 30,
    unit: '5 kg',
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Aromatic long grain basmati rice perfect for daily pulao and meals.',
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Desi Premium Toor Dal',
    altNameGujarati: '',
    category: 'atta-rice',
    price: 160,
    mrp: 185,
    stock: 50,
    unit: '1 kg',
    images: [
      'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Unpolished protein-rich Toor Dal for delicious homemade dal.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Amul Pasteurised Butter',
    altNameGujarati: '',
    category: 'dairy-bakery',
    price: 56,
    mrp: 60,
    stock: 80,
    unit: '100 g',
    images: [
      'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Taste of India! Rich creamy butter for bread toast and parathas.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Everest Garam Masala Powder',
    altNameGujarati: '',
    category: 'oil-masala',
    price: 78,
    mrp: 85,
    stock: 40,
    unit: '100 g',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Select blend of aromatic spices to enhance taste of curries.',
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Tata Salt Vacuum Evaporated Iodised Salt',
    altNameGujarati: '',
    category: 'oil-masala',
    price: 28,
    mrp: 30,
    stock: 120,
    unit: '1 kg',
    images: [
      'https://images.unsplash.com/photo-1607672632458-9eb5e69d60bf?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Desh Ka Namak. Pure iodised salt for everyday cooking.',
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Wagh Bakri Premium Leaf Tea',
    altNameGujarati: '',
    category: 'beverages',
    price: 260,
    mrp: 290,
    stock: 35,
    unit: '500 g',
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Strong, rich aroma tea for authentic Masala Chai.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Maggi 2-Minute Masala Noodles',
    altNameGujarati: '',
    category: 'snacks',
    price: 48,
    mrp: 56,
    stock: 90,
    unit: '4 Pack (280g)',
    images: [
      'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Favorite quick snack with signature tastemaker spices.',
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Balaji Classic Salted Wafers',
    altNameGujarati: '',
    category: 'snacks',
    price: 30,
    mrp: 30,
    stock: 75,
    unit: '135 g',
    images: [
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Crispy potato wafers seasoned with iodised salt.',
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Surf Excel Easy Wash Detergent Powder',
    altNameGujarati: '',
    category: 'cleaning',
    price: 145,
    mrp: 165,
    stock: 25,
    unit: '1 kg',
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Removes tough stains easily without dulling fabric colors.',
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Vim Dishwash Gel Lemon',
    altNameGujarati: '',
    category: 'cleaning',
    price: 110,
    mrp: 125,
    stock: 40,
    unit: '500 ml',
    images: [
      'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=600&q=80',
    ],
    description: 'Concentrated lemon gel for degreasing utensils quickly.',
    isFeatured: false,
    isTrending: false,
  },
];
